### ISSUE TITLE
Adds support for merging spans for prepare and affected rows

### ISSUE THREAD

**Issue by jcchavezs** [openzipkin-contrib/zipkin-go-sql#4]
`prepare` and `query` are inseparable pair of serial operations therefore presenting them as two different spans should be a matter of preference and we should be able to provide an option so user can decide whether present them as two separated spans or merge them in a single span with log records to illustrate this composed operation.

![image](https://user-images.githubusercontent.com/3075074/51744197-546f9b00-209f-11e9-9928-3507ca945a7f.png)

Any thoughts @adriancole @basvanbeek

**Comment by basvanbeek** [comment]
Typically I prepare statements only if knowing I will be querying that statement n times. Merging with the first use of the statement query seems wrong in that sense. 

I also typically prepare statements outside of the request context and use them when needed.

**Comment by codefromthecrypt** [comment]
if it is literally as bas mentions, I also agree. it could be a sign of a bug to create a new prepared statement for each query.

OTOH if the "prepare" is really assigning variables to an existing prepared statement, I would agree.. just seems it is a stretch that this is the case.

**Comment by jcchavezs** [comment]
So unfortunately for some drivers (e.g. mysql) the prepare step is made
automagically when you do a query and there is no way to avoid it.

José Carlos Chávez


Den lør. 26. jan. 2019 kl. 01:26 skrev Adrian Cole <notifications@github.com

**Comment by basvanbeek** [comment]
So you need to ask yourself do you want to see the truth (both spans) as it is calling both methods or do you want for the sake of less spans provide a slightly incorrect picture.

Personally I'd like to see what is truly happening as I would probably use that info to refactor my code to set up prepared statements in advance if I see too many of those adhoc queries pop up.

So if adding ability to merge please make the default to not do that :) That way it is a conscious decision of the consumer.

**Comment by basvanbeek** [comment]
Thinking about it, you might allow for a single span but then annotate prep and query time on the span

**Comment by jcchavezs** [comment]
Great. Do annotations like qps = query prepare start, qpe = query prepare
end, qes = query execution start & qee = query execution ends sound good?

Den tir. 5. feb. 2019, 19:06 skrev Bas van Beek <notifications@github.com:

**Comment by basvanbeek** [comment]
I’d limit to start only annotations. There will be little to no gap between the two items thus ends will be clear

**Comment by jcchavezs** [comment]
Makes sense. Will work on that this week.

**Comment by jcchavezs** [comment]
I gave it a shot some time ago but it was not possible. There is no way to differentiate when the driver calls `Prepare` and when the user does and that does not guarantee that if a span starts in the prepare (to be continued in the query), the query is being called to complete the span.
