### ISSUE TITLE
Add support for remoteEndpoint as TraceOption

### ISSUE THREAD

**Issue by jcchavezs** [openzipkin-contrib/zipkin-go-sql#7]
Currently there is no way to specify the **remoteEndpoint** for sql spans.

The way I envision it is having a TraceOption:

```go
WithRemoteEndpoint(*model.Endpoint)
```
as this will be preserver at connection level (i.e. same remote endpoint for all spans under the same connection). Remember `model.Endpoint` is a type coming from zipkin-go.

**One question:**
Is this remote endpoint being included in ALL sql spans (prepare, query, exec, etc)?

cc @adriancole @basvanbeek

**Comment by codefromthecrypt** [comment]
My take is kind.client and remoteEndpoint are reserved for those things that are actually network requests. So, each sql operation which is a remote request would have kind and remoteEndpoint

**Comment by basvanbeek** [comment]
Do note that pretty much all calls are going to wind up being network calls or possible network calls. Sometimes they are faked and handled internally if a driver doesn't support things like server prepared statements, but you have no proper way of identifying this as that is internal to database/sql.

**Comment by jcchavezs** [comment]
That was exactly my concern @basvanbeek. Prepare or affected rows are network calls depending on driver or configuration. E.g. affected rows comes by default in a MySQL result (but not necessarily in other engines) whereas prepare can be configured to be done in client or server. Even more, if we use SQLite an exec or query is not even a network call. Maybe we can say exec, ping and query should include remote endpoint or do you think none should do it?

José Carlos Chávez

**Comment by basvanbeek** [comment]
So what you might want to do is make this optional maybe even provide "profiles" for certain database drivers....

That way we can instruct what a network call is and what isn't

**Comment by jcchavezs** [comment]
Closed by https://github.com/jcchavezs/zipkin-instrumentation-sql/pull/8
